# Generated by Django 4.2 on 2023-05-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customerModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('mail', models.EmailField(max_length=250)),
                ('mobile', models.CharField(max_length=10)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=100)),
                ('status', models.IntegerField(default=1, editable=False)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
