# Generated by Django 4.2 on 2023-05-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHEEMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dogModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('breedname', models.CharField(max_length=250)),
                ('color', models.CharField(choices=[('W', 'White'), ('B', 'Black'), ('G', 'Gold'), ('GR', 'Grey')], max_length=100)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=100)),
                ('available', models.IntegerField(default=1, editable=False)),
            ],
            options={
                'db_table': 'Dogs',
            },
        ),
    ]
